const WORDS = [
  // === JLPT N5 ===
  { id: 1, word: "食べる", reading: "たべる", romaji: "taberu", meaning: "吃", jlpt: 5, example: { japanese: "朝ごはんを食べます。", before: "朝ごはんを", after: "ます。", reading: "あさごはんをたべます。", meaning: "吃早饭。" } },
  { id: 2, word: "飲む", reading: "のむ", romaji: "nomu", meaning: "喝", jlpt: 5, example: { japanese: "水を飲みます。", before: "水を", after: "みます。", reading: "みずをのみます。", meaning: "喝水。" } },
  { id: 3, word: "行く", reading: "いく", romaji: "iku", meaning: "去", jlpt: 5, example: { japanese: "学校に行きます。", before: "学校に", after: "きます。", reading: "がっこうにいきます。", meaning: "去学校。" } },
  { id: 4, word: "来る", reading: "くる", romaji: "kuru", meaning: "来", jlpt: 5, example: { japanese: "友達が来ます。", before: "友達が", after: "ます。", reading: "ともだちがきます。", meaning: "朋友来。" } },
  { id: 5, word: "帰る", reading: "かえる", romaji: "kaeru", meaning: "回去", jlpt: 5, example: { japanese: "家に帰ります。", before: "家に", after: "ります。", reading: "いえにかえります。", meaning: "回家。" } },
  { id: 6, word: "見る", reading: "みる", romaji: "miru", meaning: "看", jlpt: 5, example: { japanese: "テレビを見ます。", before: "テレビを", after: "ます。", reading: "てれびをみます。", meaning: "看电视。" } },
  { id: 7, word: "聞く", reading: "きく", romaji: "kiku", meaning: "听；问", jlpt: 5, example: { japanese: "音楽を聞きます。", before: "音楽を", after: "きます。", reading: "おんがくをききます。", meaning: "听音乐。" } },
  { id: 8, word: "読む", reading: "よむ", romaji: "yomu", meaning: "读", jlpt: 5, example: { japanese: "本を読みます。", before: "本を", after: "みます。", reading: "ほんをよみます。", meaning: "读书。" } },
  { id: 9, word: "書く", reading: "かく", romaji: "kaku", meaning: "写", jlpt: 5, example: { japanese: "手紙を書きます。", before: "手紙を", after: "きます。", reading: "てがみをかきます。", meaning: "写信。" } },
  { id: 10, word: "話す", reading: "はなす", romaji: "hanasu", meaning: "说；谈", jlpt: 5, example: { japanese: "日本語を話します。", before: "日本語を", after: "します。", reading: "にほんごをはなします。", meaning: "说日语。" } },
  { id: 11, word: "買う", reading: "かう", romaji: "kau", meaning: "买", jlpt: 5, example: { japanese: "果物を買います。", before: "果物を", after: "います。", reading: "くだものをかいます。", meaning: "买水果。" } },
  { id: 12, word: "歩く", reading: "あるく", romaji: "aruku", meaning: "走路", jlpt: 5, example: { japanese: "公園を歩きます。", before: "公園を", after: "きます。", reading: "こうえんをあるきます。", meaning: "在公园散步。" } },
  { id: 13, word: "走る", reading: "はしる", romaji: "hashiru", meaning: "跑", jlpt: 5, example: { japanese: "毎朝走ります。", before: "毎朝", after: "ります。", reading: "まいあさはしります。", meaning: "每天早上跑步。" } },
  { id: 14, word: "泳ぐ", reading: "およぐ", romaji: "oyogu", meaning: "游泳", jlpt: 5, example: { japanese: "プールで泳ぎます。", before: "プールで", after: "ぎます。", reading: "ぷーるでおよぎます。", meaning: "在游泳池游泳。" } },
  { id: 15, word: "寝る", reading: "ねる", romaji: "neru", meaning: "睡觉", jlpt: 5, example: { japanese: "十時に寝ます。", before: "十時に", after: "ます。", reading: "じゅうじにねます。", meaning: "十点睡觉。" } },
  { id: 16, word: "起きる", reading: "おきる", romaji: "okiru", meaning: "起床", jlpt: 5, example: { japanese: "六時に起きます。", before: "六時に", after: "きます。", reading: "ろくじにおきます。", meaning: "六点起床。" } },
  { id: 17, word: "勉強", reading: "べんきょう", romaji: "benkyou", meaning: "学习", jlpt: 5, example: { japanese: "日本語を勉強します。", before: "日本語を", after: "します。", reading: "にほんごをべんきょうします。", meaning: "学习日语。" } },
  { id: 18, word: "仕事", reading: "しごと", romaji: "shigoto", meaning: "工作", jlpt: 5, example: { japanese: "仕事は大変です。", before: "", after: "は大変です。", reading: "しごとはたいへんです。", meaning: "工作很辛苦。" } },
  { id: 19, word: "友達", reading: "ともだち", romaji: "tomodachi", meaning: "朋友", jlpt: 5, example: { japanese: "友達と遊びます。", before: "", after: "と遊びます。", reading: "ともだちとあそびます。", meaning: "和朋友玩。" } },
  { id: 20, word: "先生", reading: "せんせい", romaji: "sensei", meaning: "老师", jlpt: 5, example: { japanese: "先生に聞きます。", before: "", after: "に聞きます。", reading: "せんせいにききます。", meaning: "问老师。" } },
  { id: 21, word: "学生", reading: "がくせい", romaji: "gakusei", meaning: "学生", jlpt: 5, example: { japanese: "私は学生です。", before: "私は", after: "です。", reading: "わたしはがくせいです。", meaning: "我是学生。" } },
  { id: 22, word: "学校", reading: "がっこう", romaji: "gakkou", meaning: "学校", jlpt: 5, example: { japanese: "学校は楽しいです。", before: "", after: "は楽しいです。", reading: "がっこうはたのしいです。", meaning: "学校很开心。" } },
  { id: 23, word: "病院", reading: "びょういん", romaji: "byouin", meaning: "医院", jlpt: 5, example: { japanese: "病院に行きます。", before: "", after: "に行きます。", reading: "びょういんにいきます。", meaning: "去医院。" } },
  { id: 24, word: "駅", reading: "えき", romaji: "eki", meaning: "车站", jlpt: 5, example: { japanese: "駅は近いです。", before: "", after: "は近いです。", reading: "えきはちかいです。", meaning: "车站很近。" } },
  { id: 25, word: "部屋", reading: "へや", romaji: "heya", meaning: "房间", jlpt: 5, example: { japanese: "部屋をきれいにします。", before: "", after: "をきれいにします。", reading: "へやをきれいにします。", meaning: "把房间打扫干净。" } },
  { id: 26, word: "大きい", reading: "おおきい", romaji: "ookii", meaning: "大的", jlpt: 5, example: { japanese: "この部屋は大きいです。", before: "この部屋は", after: "です。", reading: "このへやはおおきいです。", meaning: "这个房间很大。" } },
  { id: 27, word: "小さい", reading: "ちいさい", romaji: "chiisai", meaning: "小的", jlpt: 5, example: { japanese: "小さい猫が好きです。", before: "", after: "猫が好きです。", reading: "ちいさいねこがすきです。", meaning: "喜欢小猫。" } },
  { id: 28, word: "新しい", reading: "あたらしい", romaji: "atarashii", meaning: "新的", jlpt: 5, example: { japanese: "新しい本を買いました。", before: "", after: "本を買いました。", reading: "あたらしいほんをかいました。", meaning: "买了新书。" } },
  { id: 29, word: "古い", reading: "ふるい", romaji: "furui", meaning: "旧的", jlpt: 5, example: { japanese: "古いお寺があります。", before: "", after: "お寺があります。", reading: "ふるいおてらがあります。", meaning: "有古老的寺庙。" } },
  { id: 30, word: "高い", reading: "たかい", romaji: "takai", meaning: "高的；贵的", jlpt: 5, example: { japanese: "この山は高いです。", before: "この山は", after: "です。", reading: "このやまはたかいです。", meaning: "这座山很高。" } },
  { id: 31, word: "安い", reading: "やすい", romaji: "yasui", meaning: "便宜的", jlpt: 5, example: { japanese: "このりんごは安いです。", before: "このりんごは", after: "です。", reading: "このりんごはやすいです。", meaning: "这个苹果很便宜。" } },
  { id: 32, word: "美味しい", reading: "おいしい", romaji: "oishii", meaning: "好吃的", jlpt: 5, example: { japanese: "この料理は美味しいです。", before: "この料理は", after: "です。", reading: "このりょうりはおいしいです。", meaning: "这道菜很好吃。" } },
  { id: 33, word: "楽しい", reading: "たのしい", romaji: "tanoshii", meaning: "快乐的", jlpt: 5, example: { japanese: "旅行は楽しいです。", before: "旅行は", after: "です。", reading: "りょこうはたのしいです。", meaning: "旅行很快乐。" } },
  { id: 34, word: "難しい", reading: "むずかしい", romaji: "muzukashii", meaning: "难的", jlpt: 5, example: { japanese: "日本語は難しいです。", before: "日本語は", after: "です。", reading: "にほんごはむずかしいです。", meaning: "日语很难。" } },
  { id: 35, word: "元気", reading: "げんき", romaji: "genki", meaning: "精神好；健康", jlpt: 5, example: { japanese: "元気ですか。", before: "", after: "ですか。", reading: "げんきですか。", meaning: "你好吗？" } },
  { id: 36, word: "好き", reading: "すき", romaji: "suki", meaning: "喜欢", jlpt: 5, example: { japanese: "音楽が好きです。", before: "音楽が", after: "です。", reading: "おんがくがすきです。", meaning: "喜欢音乐。" } },
  { id: 37, word: "大好き", reading: "だいすき", romaji: "daisuki", meaning: "非常喜欢", jlpt: 5, example: { japanese: "猫が大好きです。", before: "猫が", after: "です。", reading: "ねこがだいすきです。", meaning: "非常喜欢猫。" } },
  { id: 38, word: "食べ物", reading: "たべもの", romaji: "tabemono", meaning: "食物", jlpt: 5, example: { japanese: "日本の食べ物が好きです。", before: "日本の", after: "が好きです。", reading: "にほんのたべものがすきです。", meaning: "喜欢日本食物。" } },
  { id: 39, word: "飲み物", reading: "のみもの", romaji: "nomimono", meaning: "饮料", jlpt: 5, example: { japanese: "冷たい飲み物が欲しいです。", before: "冷たい", after: "が欲しいです。", reading: "つめたいのみものがほしいです。", meaning: "想要冷饮。" } },
  { id: 40, word: "水", reading: "みず", romaji: "mizu", meaning: "水", jlpt: 5, example: { japanese: "水をください。", before: "", after: "をください。", reading: "みずをください。", meaning: "请给我水。" } },
  { id: 41, word: "お茶", reading: "おちゃ", romaji: "ocha", meaning: "茶", jlpt: 5, example: { japanese: "お茶を飲みましょう。", before: "", after: "を飲みましょう。", reading: "おちゃをのみましょう。", meaning: "喝茶吧。" } },
  { id: 42, word: "天気", reading: "てんき", romaji: "tenki", meaning: "天气", jlpt: 5, example: { japanese: "今日はいい天気です。", before: "今日はいい", after: "です。", reading: "きょうはいいてんきです。", meaning: "今天天气好。" } },
  { id: 43, word: "時間", reading: "じかん", romaji: "jikan", meaning: "时间", jlpt: 5, example: { japanese: "時間がありません。", before: "", after: "がありません。", reading: "じかんがありません。", meaning: "没有时间。" } },
  { id: 44, word: "名前", reading: "なまえ", romaji: "namae", meaning: "名字", jlpt: 5, example: { japanese: "名前は何ですか。", before: "", after: "は何ですか。", reading: "なまえはなんですか。", meaning: "你叫什么名字？" } },
  { id: 45, word: "電車", reading: "でんしゃ", romaji: "densha", meaning: "电车", jlpt: 5, example: { japanese: "電車で行きます。", before: "", after: "で行きます。", reading: "でんしゃでいきます。", meaning: "坐电车去。" } },
  { id: 46, word: "飛行機", reading: "ひこうき", romaji: "hikouki", meaning: "飞机", jlpt: 5, example: { japanese: "飛行機で旅行します。", before: "", after: "で旅行します。", reading: "ひこうきでりょこうします。", meaning: "坐飞机旅行。" } },
  { id: 47, word: "自動車", reading: "じどうしゃ", romaji: "jidousha", meaning: "汽车", jlpt: 5, example: { japanese: "自動車を運転します。", before: "", after: "を運転します。", reading: "じどうしゃをうんてんします。", meaning: "开车。" } },
  { id: 48, word: "花", reading: "はな", romaji: "hana", meaning: "花", jlpt: 5, example: { japanese: "きれいな花ですね。", before: "きれいな", after: "ですね。", reading: "きれいなはなですね。", meaning: "漂亮的花啊。" } },
  { id: 49, word: "山", reading: "やま", romaji: "yama", meaning: "山", jlpt: 5, example: { japanese: "山に登ります。", before: "", after: "に登ります。", reading: "やまにのぼります。", meaning: "爬山。" } },
  { id: 50, word: "川", reading: "かわ", romaji: "kawa", meaning: "河", jlpt: 5, example: { japanese: "この川は長いです。", before: "この", after: "は長いです。", reading: "このかわはながいです。", meaning: "这条河很长。" } },
  { id: 51, word: "海", reading: "うみ", romaji: "umi", meaning: "海", jlpt: 5, example: { japanese: "海で泳ぎます。", before: "", after: "で泳ぎます。", reading: "うみでおよぎます。", meaning: "在海里游泳。" } },
  { id: 52, word: "日本", reading: "にほん", romaji: "nihon", meaning: "日本", jlpt: 5, example: { japanese: "日本に行きたいです。", before: "", after: "に行きたいです。", reading: "にほんにいきたいです。", meaning: "想去日本。" } },
  { id: 53, word: "日本語", reading: "にほんご", romaji: "nihongo", meaning: "日语", jlpt: 5, example: { japanese: "日本語を勉強しています。", before: "", after: "を勉強しています。", reading: "にほんごをべんきょうしています。", meaning: "正在学习日语。" } },
  { id: 54, word: "毎日", reading: "まいにち", romaji: "mainichi", meaning: "每天", jlpt: 5, example: { japanese: "毎日日本語を話します。", before: "", after: "日本語を話します。", reading: "まいにちにほんごをはなします。", meaning: "每天说日语。" } },
  { id: 55, word: "今日", reading: "きょう", romaji: "kyou", meaning: "今天", jlpt: 5, example: { japanese: "今日は何曜日ですか。", before: "", after: "は何曜日ですか。", reading: "きょうはなんようびですか。", meaning: "今天是星期几？" } },
  { id: 56, word: "明日", reading: "あした", romaji: "ashita", meaning: "明天", jlpt: 5, example: { japanese: "明日学校に行きます。", before: "", after: "学校に行きます。", reading: "あしたがっこうにいきます。", meaning: "明天去学校。" } },
  { id: 57, word: "昨日", reading: "きのう", romaji: "kinou", meaning: "昨天", jlpt: 5, example: { japanese: "昨日映画を見ました。", before: "", after: "映画を見ました。", reading: "きのうえいがをみました。", meaning: "昨天看了电影。" } },
  { id: 58, word: "猫", reading: "ねこ", romaji: "neko", meaning: "猫", jlpt: 5, example: { japanese: "猫が可爱いです。", before: "", after: "が可爱いです。", reading: "ねこがかわいいです。", meaning: "猫很可爱。" } },
  { id: 59, word: "犬", reading: "いぬ", romaji: "inu", meaning: "狗", jlpt: 5, example: { japanese: "犬が好きです。", before: "", after: "が好きです。", reading: "いぬがすきです。", meaning: "喜欢狗。" } },
  { id: 60, word: "家族", reading: "かぞく", romaji: "kazoku", meaning: "家人", jlpt: 5, example: { japanese: "家族は四人です。", before: "", after: "は四人です。", reading: "かぞくはよにんです。", meaning: "家里有四口人。" } },

  // === JLPT N4 ===
  { id: 61, word: "説明", reading: "せつめい", romaji: "setsumei", meaning: "说明", jlpt: 4, example: { japanese: "もう一度説明してください。", before: "もう一度", after: "してください。", reading: "もういちどせつめいしてください。", meaning: "请再说明一次。" } },
  { id: 62, word: "経験", reading: "けいけん", romaji: "keiken", meaning: "经验", jlpt: 4, example: { japanese: "いい経験になりました。", before: "いい", after: "になりました。", reading: "いいけいけんになりました。", meaning: "成为了一次好经验。" } },
  { id: 63, word: "準備", reading: "じゅんび", romaji: "junbi", meaning: "准备", jlpt: 4, example: { japanese: "旅行の準備をします。", before: "旅行の", after: "をします。", reading: "りょこうのじゅんびをします。", meaning: "做旅行准备。" } },
  { id: 64, word: "約束", reading: "やくそく", romaji: "yakusoku", meaning: "约定", jlpt: 4, example: { japanese: "明日の約束を忘れないで。", before: "明日の", after: "を忘れないで。", reading: "あしたのやくそくをわすれないで。", meaning: "别忘了明天的约定。" } },
  { id: 65, word: "連絡", reading: "れんらく", romaji: "renraku", meaning: "联系", jlpt: 4, example: { japanese: "後で連絡します。", before: "後で", after: "します。", reading: "あとでれんらくします。", meaning: "之后联系你。" } },
  { id: 66, word: "紹介", reading: "しょうかい", romaji: "shoukai", meaning: "介绍", jlpt: 4, example: { japanese: "自己紹介をしてください。", before: "自己", after: "をしてください。", reading: "じこしょうかいをしてください。", meaning: "请做自我介绍。" } },
  { id: 67, word: "相談", reading: "そうだん", romaji: "soudan", meaning: "商量", jlpt: 4, example: { japanese: "先生に相談しました。", before: "先生に", after: "しました。", reading: "せんせいにそうだんしました。", meaning: "和老师商量了。" } },
  { id: 68, word: "残念", reading: "ざんねん", romaji: "zannen", meaning: "遗憾；可惜", jlpt: 4, example: { japanese: "残念ですが、行けません。", before: "", after: "ですが、行けません。", reading: "ざんねんですが、いけません。", meaning: "很遗憾，去不了。" } },
  { id: 69, word: "心配", reading: "しんぱい", romaji: "shinpai", meaning: "担心", jlpt: 4, example: { japanese: "心配しないでください。", before: "", after: "しないでください。", reading: "しんぱいしないでください。", meaning: "请不要担心。" } },
  { id: 70, word: "大切", reading: "たいせつ", romaji: "taisetsu", meaning: "重要的", jlpt: 4, example: { japanese: "友達は大切です。", before: "友達は", after: "です。", reading: "ともだちはたいせつです。", meaning: "朋友很重要。" } },
  { id: 71, word: "丁寧", reading: "ていねい", romaji: "teinei", meaning: "礼貌的；仔细的", jlpt: 4, example: { japanese: "丁寧に説明します。", before: "", after: "に説明します。", reading: "ていねいにせつめいします。", meaning: "仔细地说明。" } },
  { id: 72, word: "特別", reading: "とくべつ", romaji: "tokubetsu", meaning: "特别", jlpt: 4, example: { japanese: "今日は特別な日です。", before: "今日は", after: "な日です。", reading: "きょうはとくべつなひです。", meaning: "今天是特别的日子。" } },
  { id: 73, word: "自由", reading: "じゆう", romaji: "jiyuu", meaning: "自由", jlpt: 4, example: { japanese: "自由に使ってください。", before: "", after: "に使ってください。", reading: "じゆうにつかってください。", meaning: "请自由使用。" } },
  { id: 74, word: "親切", reading: "しんせつ", romaji: "shinsetsu", meaning: "亲切的", jlpt: 4, example: { japanese: "親切な人です。", before: "", after: "な人です。", reading: "しんせつなひとです。", meaning: "是个亲切的人。" } },
  { id: 75, word: "便利", reading: "べんり", romaji: "benri", meaning: "方便的", jlpt: 4, example: { japanese: "この駅は便利です。", before: "この駅は", after: "です。", reading: "このえきはべんりです。", meaning: "这个车站很方便。" } },
  { id: 76, word: "複雑", reading: "ふくざつ", romaji: "fukuzatsu", meaning: "复杂的", jlpt: 4, example: { japanese: "この問題は複雑です。", before: "この問題は", after: "です。", reading: "このもんだいはふくざつです。", meaning: "这个问题很复杂。" } },
  { id: 77, word: "環境", reading: "かんきょう", romaji: "kankyou", meaning: "环境", jlpt: 4, example: { japanese: "環境を守りましょう。", before: "", after: "を守りましょう。", reading: "かんきょうをまもりましょう。", meaning: "保护环境吧。" } },
  { id: 78, word: "習慣", reading: "しゅうかん", romaji: "shuukan", meaning: "习惯", jlpt: 4, example: { japanese: "早起きの習慣があります。", before: "早起きの", after: "があります。", reading: "はやおきのしゅうかんがあります。", meaning: "有早起的习惯。" } },
  { id: 79, word: "趣味", reading: "しゅみ", romaji: "shumi", meaning: "爱好", jlpt: 4, example: { japanese: "趣味は読書です。", before: "", after: "は読書です。", reading: "しゅみはどくしょです。", meaning: "爱好是读书。" } },
  { id: 80, word: "留学", reading: "りゅうがく", romaji: "ryuugaku", meaning: "留学", jlpt: 4, example: { japanese: "日本に留学したいです。", before: "日本に", after: "したいです。", reading: "にほんにりゅうがくしたいです。", meaning: "想去日本留学。" } }
];

function getWordsByJlpt(level) {
  return WORDS.filter(w => w.jlpt === level);
}

function getRandomWords(words, count) {
  const shuffled = [...words].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}
